# Generated by Django 6.0.7 on 2026-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Portfolio', max_length=200)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('banner_text', models.TextField(default="Welcome to my portfolio • Explore my work • Let's create something amazing", help_text='Text that scrolls across the banner. Use • to separate phrases.')),
                ('about_text', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('dribbble', 'Dribbble'), ('behance', 'Behance')], max_length=50)),
                ('url', models.URLField()),
                ('username', models.CharField(blank=True, help_text='Display name/handle', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
