# Generated by Django 6.0.7 on 2026-07-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_background',
            field=models.ImageField(blank=True, help_text='Background image for the About section', null=True, upload_to='about_bg/'),
        ),
    ]
