# Generated by Django 6.0.7 on 2026-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_employmenthistory_remove_sitesetting_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Square profile image shown at the top right of the banner', null=True, upload_to='profile/'),
        ),
    ]
