# Generated by Django 6.0.7 on 2026-10-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_sitesetting_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=50, help_text='Proficiency percentage from 0 to 100')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number shown in the Contact section', max_length=30),
        ),
    ]
