# Generated by Django 6.0.7 on 2026-10-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill_sitesetting_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='banner_text',
        ),
    ]
